---
title: "My Projects"
output: html_document
---
```{r echo=FALSE, message=FALSE, warning="FALSE"}
#install.packages("pander")
library(pander)
library(dplyr)
library(tidyverse)
library(kableExtra)
library(reshape2)
```

<section id="body2">
## Data Science {.main-heading}  

```{r echo=FALSE, message=FALSE, warning="FALSE"}
projectNames <- c("Air Pollution", "Student Housing Insecurity", "Classification and Regression Trees", "Modeling Accuracy and Test Prediction Errors")

projectHyperlinks <- c("https://introdsci.github.io/DataScience-kcrisci94/index", "https://kcrisci94.github.io/MATH456Project/", "project_files/hw09-CART-assignment.html", "project_files/classification-assignment.html")

projectDesc <- c("This project uses a collection of measurements on harmful particles in the atmosphere at several different locations in California. It uses this data to determine which geographic locations have the highest levels of air pollution. It then uses populations in those general regions to determine if population has an affect on the air pollution levels.", 
                 "This project builds on a previous study by Dr. Wilking in 2019 about the housing insecurity and homelessness of students in recent years. It also focuses on how the Camp Fire impacted the students' housing situations. The goal of this study was to try to reproduce the findings of Dr. Wilking, and then take a look at how missing data affects the results of the study.",
                 "This project gives information about classification of data and regression trees. It includes topics such as pruning trees, bagging, and boosting. It also covers random forests. In addition to the information, this project uses an example dataset to show how to incorporate these topics to analyze the data using R code.", 
                 "This project explores how different classification algorithms can yield very different predictive results. It is therefore important to test how well your models perform with test data, and compare the results with other algorithms in order to find a model that best works for your data. This project uses an example dataset and generates  four different models: GLM, LDA, QDA, and KNN. It then shows how to compare the accuracy and test error between these four models using R code.")
```
<section class="project_Table">

<a href="`r projectHyperlinks[1]`"> `r projectNames[1]`</a>
<p class="description">`r projectDesc[1]`</p>

<a href="`r projectHyperlinks[2]`"> `r projectNames[2]`</a>
<p class="description">`r projectDesc[2]`</p>

<a href="`r projectHyperlinks[3]`"> `r projectNames[3]`</a>
<p class="description">`r projectDesc[3]`</p>

<a href="`r projectHyperlinks[4]`"> `r projectNames[4]`</a>
<p class="description">`r projectDesc[4]`</p>
</section>

## Web Design {.main-heading}

```{r echo=FALSE, message=FALSE, warning="FALSE"}
web <- read.table("./project_files/webList.csv", sep="\t", header=TRUE)
web <- as.data.frame(web)
webNames <- web$Project
webHyperlinks <- web$Link
webDesc <- web$Description
```

<section class="project_Table">
<a href="`r webHyperlinks[1]`"> `r webNames[1]`</a>
<p class="description">`r webDesc[1]`</p>


<a href="`r webHyperlinks[2]`"> `r webNames[2]`</a>
<p class="description">`r webDesc[2]`</p>

<a href="`r webHyperlinks[3]`"> `r webNames[3]`</a>
<p class="description">`r webDesc[3]`</p>
</section>



</section>
