---
title: "Data Science and COVID-19"
author: "Kaleb Crisci"
date: "3/31/2020"
output: html_document
---

The Corona Virus (COVID-19) has become a major worldwide pandemic. On January 11, 2020, China reported its first death. Since then, the virus has spread to several other countries at an exponential growth rate. The pandemic has become a major interest for data scientists. Around the world, individuals and governments are tracking reported cases of COVID-19, recording data and publicizing it so that others can perform analysis as well. There are several approaches data scientists are taking to both increase understanding and awareness of this outbreak, and to try to find ways to improve how we are handling the virus.   

One of the main goals of data scientists at this point in time is to track and analyse data about this virus. This data includes the number of confirmed cases, the location of each reported case, the date that the case was recorded, the number of deaths from COVID-19, the age of infected individuals and many more. From this information, data scientists are able create summary statistics about not only how the virus is spreading, but how the virus is affecting different groups of people. They are building graphical representations that show the increasing rate of new cases that appear daily in specific parts of the world and with that, the death rates. They also were able to determine the mortality rates of the virus based on age. You can find information on the statistical analysis done by Our World in Data [here](https://ourworldindata.org/coronavirus).   

Another goal of data scientists during this epidemic is the development of reliable methods to test for COVID-19. There are a few approaches to this, but most that I've been able to find so far have used machine learning to accomplish this. One particular study I found is attempting to use machine learning to analyse chest X-Rays and find patterns used to predict whether a person is infected with COVID-19. The appeal of this idea is that X-Rays are inexpensive and widely available to to healthcare practitioners. You can read about this study [here](https://towardsdatascience.com/how-to-use-covid-cxr-to-predict-covid-19-on-chest-x-rays-with-explainable-ai-c05cb07d5f0f). If you would like to contribute to the study, the github repository is also available [here](https://github.com/aildnont/covid-cxr).   
   
Finally, a third goal of data scientists is to help discover treatments for the infected that might help to reduce the duration of symptoms, lower the mortality rates, and ultimately defeat the virus. One interesting article I found was describes how a group of graduates from the Data Science Institute at Columbia University have been developing algorithms that can computationally generate and screen hundreds of millions of antibodies to determine which ones could potentially be effective in fighting COVID-19. They run a majority of the tests in the computer to reduce the number of failed tests in the lab (saving years of research and testing time). After the preliminary computer testing, they can move to animal testing and then to human testing. They estimate that by performing the majority of the testing through a computer and having the computer identify which antibodies would be effictive against COVID-19, they would be able to have a treatment ready for patients before the end of 2020. To read more about this article, [click here](https://healthitanalytics.com/news/data-scientists-use-machine-learning-to-discover-covid-19-treatments).   

Given more time to focus on my own projects, I would really like to participate in either the study of analyzing X-Rays to create models to predict if a person in infected or not. This enters into the area of Artificial Intelligence, which is one of my primary interests. I was also very intrigued by the study that tests antibodies to develop effective treatments. I had no idea that scientists were able to design and create their own antibodies.   

Sources:  
* [Our World in Data: Coronavirus Disease Statistics and Research](https://ourworldindata.org/coronavirus)   
* [Use Machine Learning to Identify COVID-19 on Chest Xrays](https://towardsdatascience.com/how-to-use-covid-cxr-to-predict-covid-19-on-chest-x-rays-with-explainable-ai-c05cb07d5f0f)   
* [Use Machine Learning to Discover COVID-19 Treatments](https://healthitanalytics.com/news/data-scientists-use-machine-learning-to-discover-covid-19-treatments)